### PR TITLE
Generalize mcmcRocPrc for various kinds of input objects

### LINKED ISSUE #5: MCMC_roc_prc: generalize for other input
including JAGS/BUGS

### PR DESCRIPTION
**Pull request by andybega**
- Closes #5 
- mcmcRocPrc() becomes a generic function; methods address different input types, like mcmcRocPrc.rjags() for "rjags" objects; it returns objects of class "mcmcRocPrc", which has the previously added print, etc. methods. 
- all methods use the same class constructor to make new "mcmcRocPrc" class objects, new_mcmcRocPrc(); this makes sure that output is consistent accross implementation for different input types, and also avoids having to repeat code over and over again in each method
- the default mcmcRocPrc() method takes a matrix of predicted probabilities (N cases rows, N posterior samples columns) and a vector of observed outcomes (length = N cases) as inputs; this should allow an escape hatch that can handle any type of input even if a method for that particular output type is not available
- methods right now cover input from packages (with class): rstan (stanfit) rstanarm (stanreg), brms (brmsfit), rjags (jags), R2jags (rjags), runjags (runjags), and MCMCpack (mcmc)
- there is **no method** to accommodate input from R2WinBUGS. The package has been last updated on CRAN in 2015, and it seems clear that STAN is the successor. If someone can add a logit BUGS example I can add a method, though. 
- adds tests for most of the new methods, although not 100% for all lines; also for this reason adds several models in `tests/testdata`. I added these under `tests`, otherwise if they are in `data` the package installed size is > 5 MB, which generates a R check NOTE, and also noticeably slows `library(BayesPostEst)`. 

No R check ERRORs, WARNINGs, or NOTEs. ([Travis-CI on my fork](https://travis-ci.com/github/andybega/BayesPostEst))

### CODE REVIEW

**Comment by jayrobwilliams** [comment]
This looks fantastic! When I have some time I'll probably follow a similar approach with `mcmcReg()` and `mcmcTab()` using methods and class constructor functions instead of the giant block of conditionals at the top of each right now.

**Comment by andybega** [comment]
Thanks! I wasn't sure if using generic + methods ends up making it more complicated than it needs to be.

**Comment by jkarreth** [comment]
Thank you indeed @andybega , this is great! I'm working on getting a BUGS object, hopefully within 1-2 days.

**Comment by jkarreth** [comment]
I added a BUGS object representing output from a logit model: [data/bugs_logit.rda](https://github.com/ShanaScogin/BayesPostEst/blob/master/data/bugs_logit.rda)

This was created by adapting [data-raw/jags_logit.R](https://github.com/ShanaScogin/BayesPostEst/blob/master/data-raw/jags_logit.R) to R2OpenBUGS.

(Note that the actual script to create `bugs_logit.rda` is not on Github, I asked someone else to run it on their machine. Hope this is OK for future CRAN uploads etc.)

@andybega @jayrobwilliams  does this give you enough for the adjusting for BUGS objects as input?

**Pull request merged**
