### PR TITLE
Codecov and expanded tests

### PR DESCRIPTION
**Pull request by andybega**
Hello,
I took a stab at some easy "fluff" tasks to become a bit more familiar with the package structure. The commits in this pull request:

- Update the README to show install instructions for the CRAN version (and congrats). Also, `install_github` lives in `remotes` now.
- Simplify existing tests. I noticed that the existing test duplicated the logit and probit JAGS model estimation, so I added them as package data instead (with scripts to create them in `data-raw`.)
    + E.g. instead of setting up the data and estimating the model, `data("jags_logit")` will return the fitted JAGS model used in some examples and tests. 
    + This should make the examples easier too, e.g. the previous example in `mcmcTab()` that was wrapped in `\donttest{}` is now shorter and quick enough to run during R build and check. 
- Add some new tests. This was covering some minor previous edge cases. I see that the biggest remaining chunk now is the slow code in `mcmcRocPrc.R` and that it's skipped because of #25. Test coverage started at 61% and should now be 89%. 
- Add codecov for travis. I think you'll need to turn on this repo on codecov.io (I login with GitHub) for this to work. Here's what I get in any case: https://codecov.io/gh/andybega/BayesPostEst. I also added a badge for this to the repo although it won't show anything until codecov is turned on. 
- Add a NEWS.md file / changelog. 
- Fix ROPE input validation for `mcmcTab()` and `mcmcFDplot()`. It would previously work with nonsensical input, e.g. "a" would not error out. I added a function, `check_ROPE_argument()`, to perform the check. (https://github.com/ShanaScogin/BayesPostEst/issues/44). 
- Fix the travis-ci config file. The previous version was not running the R build and check commands on the package--instead only checking the installed rstan version. (https://github.com/ShanaScogin/BayesPostEst/issues/45)

Passes tests and R check with no errors, warnings, or notes. 

Screen Shot 2019-08-30 at 21 56 33

### CODE REVIEW

**Comment by jkarreth** [comment]
Awesome! Thank you for working on this. I've claimed #44 for now, but if you already have a solution that I didn't see, please follow up there on that issue. Thanks again!

**Comment by andybega** [comment]
@jkarreth, hello, yes, there's a fix for #44 in one of these.

**Comment by andybega** [comment]
Hi @ShanaScogin, I merged in the commits you guys have done over the past few days.

**Comment by ShanaScogin** [comment]
I know I approved this merge, but I don't know if I ever said thank you - this all looks amazing! I'll be in an out for most of this week, but do send me a message if I'm not getting to something you need me to do fast enough. Thanks again! I look forward to working together more!

**Comment by andybega** [comment]
You're welcome! This is a lot of fun to work on, and I'm happy that you appreciate it. I had a couple of spare hours at the end of the month to put into this, for now it's back to regular work for me.

**Comment by jkarreth** [comment]
Agreed, thanks so much, this is really great. 👍

**Pull request merged**
